Map<String, String> textsAr = {
  "Fajr": "الفجْر",
  "Sunrise": "الشروق",
  "Dhuhr": "الظُّهْر",
  "Asr": "العَصر",
  "Sunset": "غروب الشمس",
  "Maghrib": "المَغرب",
  "Isha": "العِشاء",
  "Imsak": "إمساك",
  "Midnight": "منتصف الليل",
  "Select": "حدد الدولة والمدينة",
  "Submit": "متابعة",
  "latitude Adjustment Method": "طريقة تعديل خط العرض",
  "Timezone": "وحدة زمنية",
  "School": "مدرسة",
  "Name": "اسم",
  "Country": "دولة",
  "City": "مدينة",
  "Loading": "جاري تحميل ...",
  "Home": "الصفحة الرئيسية",
  "Bookmark": "الاشارة المرجعية",
  "Favorite": "المفضل",
  "verses": "آياتها",
  "Azkar": "أذكار",
  "Repetition": "تكرار",
  "saveMark": "حفظ علامة",
  "GoToTag": "انتقال الى العلامة",
  "Contents": "الفهرس",
  "Pages": "الصفحات",
  "SealPrayer": "دعاء الختم",
  "TimePrayer": "وقت الصلاة",
  "Ayah": "آيات",
  "Quran": "القرآن",
  "Settings": "إعدادات",
  "darkMode": "الوضع المظلم",
  "lightMode": "وضع الضوء",
  "language": "اللغة الإنجليزية",
  "updateLocation": "تحديث الموقع",
};

Map<String, String> textsEn = {
  "Fajr": "Fajr",
  "Sunrise": "Sunrise",
  "Dhuhr": "Dhuhr",
  "Asr": "Asr",
  "Sunset": "Sunset",
  "Maghrib": "Maghrib",
  "Isha": "Isha",
  "Imsak": "Imsak",
  "Midnight": "Midnight",
  "Select": "Select Country and City",
  "Submit": "Submit",
  "latitude Adjustment Method": "latitude Adjustment Method",
  "Timezone": "Timezone",
  "School": "School",
  "Name": "Name",
  "Country": "Country",
  "City": "City",
  "Loading": "Loading  ...",
  "Home": "Home",
  "Bookmark": "Bookmark",
  "Favorite": "Favorite",
  "verses": "verses",
  "Azkar": "Azkar",
  "Repetition": "Repetition",
  "saveMark": "Save Mark",
  "GoToTag": "Go To Tag",
  "Contents": "Contents",
  "Pages": "Pages",
  "SealPrayer": "Seal Prayer",
  "TimePrayer": "Time Prayer",
  "Ayah": "Ayah",
  "Quran": "Qoran",
  "Settings": "Settings",
  "darkMode": "Dark Mode",
  "lightMode": "Light Mode",
  "language": "language Arabic",
  "updateLocation": "Update Location",
};
