Map<String, String> textsAr = {
  "Fajr": "الفجْر",
  "Sunrise": "الشروق",
  "Dhuhr": "الظُّهْر",
  "Asr": "العَصر",
  "Sunset": "غروب الشمس",
  "Maghrib": "المَغرب",
  "Isha": "العِشاء",
  "Imsak": "إمساك",
  "Midnight": "منتصف الليل",
  "Select": "حدد الدولة والمدينة",
  "Submit": "متابعة",
  "latitude Adjustment Method": "طريقة تعديل خط العرض",
  "Timezone": "وحدة زمنية",
  "School": "مدرسة",
  "Name": "اسم",
  "Country": "دولة",
  "City": "مدينة",
  "Loading": "جاري تحميل ...",
  "Home": "الصفحة الرئيسية",
  "Bookmark": "الاشارة المرجعية",
  "Favorite": "المفضل",
  "verses": "آياتها",
  "Azkar": "أذكار",
  "Repetition": "Repetition",
};

Map<String, String> textsEn = {
  "Fajr": "Fajr",
  "Sunrise": "Sunrise",
  "Dhuhr": "Dhuhr",
  "Asr": "Asr",
  "Sunset": "Sunset",
  "Maghrib": "Maghrib",
  "Isha": "Isha",
  "Imsak": "Imsak",
  "Midnight": "Midnight",
  "Select": "Select Country and City",
  "Submit": "Submit",
  "latitude Adjustment Method": "latitude Adjustment Method",
  "Timezone": "Timezone",
  "School": "School",
  "Name": "Name",
  "Country": "Country",
  "City": "City",
  "Loading": "Loading  ...",
  "Home": "Home",
  "Bookmark": "Bookmark",
  "Favorite": "Favorite",
  "verses": "verses",
  "Azkar": "Azkar",
  "Repetition": "Repetition",
};
